baseURL = "https://www.janineforsyth.com/"
languageCode = "en-us"
title = "Janine Forsyth"
theme = "ananke"
disqusShortname = "janineforsyth"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  favicon = ""
  site_logo = ""
  description = "I want to help you reach your destiny."
  facebook = "https://www.facebook.com/Its-all-about-Jesus-609323252483276"
#  facebook = "https://www.facebook.com/JESUS-is-lief-vir-jou-341055579383077"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sea-header.jpg"
  recent_posts_number = 9